repos:
  - repo: local
    hooks:
      - id: update-generated
        name: Update generated files (rizoma)
        entry: python3 scripts/precommit/update_generated.py
        language: python
        pass_filenames: false
        always_run: true

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--line-length=88"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: ["--fix"]
