name: Deploy to GitHub Pages (gh-pages)

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-generated:
    name: Validate generated files are up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then
            pip install -r scripts/requirements.txt
          fi

      - name: Run exporter
        run: python3 scripts/export_file.py all

      - name: Fail if generated files changed
        run: |
          if ! git diff --quiet --exit-code; then
            echo "\nGenerated files are out of date. Run 'python3 scripts/export_file.py all' locally and commit the changes.\n"
            git --no-pager status --porcelain
            git --no-pager diff --name-only
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    name: Build and publish to gh-pages
    needs: validate-generated
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # allow the workflow to push back to the repo using the provided token
          persist-credentials: true
          # fetch full history so tags/branches can be pushed reliably
          fetch-depth: 0

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          # publish_branch: gh-pages (default)
          user_name: silvanoneto
          user_email: dev@silvanoneto.com

      - name: Ensure GitHub Pages source is set to gh-pages (API)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          api="https://api.github.com/repos/${{ github.repository }}/pages"
          echo "PUT $api -> set source to gh-pages"
          curl -sS -X PUT \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d '{"source":{"branch":"master","path":"/"}}' \
            "$api" | jq -r '.url, .status, .cname' || true

      - name: Show Pages status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          api="https://api.github.com/repos/${{ github.repository }}/pages"
          echo "GET $api -> pages info"
          curl -sS -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$api" | jq || true
