name: Deploy to GitHub Pages (gh-pages)

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and publish to gh-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          # publish_branch: gh-pages (default)
          # You can customize the committer name/email if desired
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
