name: Deploy to GitHub Pages (gh-pages)

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and publish to gh-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # allow the workflow to push back to the repo using the provided token
          persist-credentials: true
          # fetch full history so tags/branches can be pushed reliably
          fetch-depth: 0

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          # publish_branch: gh-pages (default)
          user_name: silvanoneto
          user_email: dev@silvanoneto.com
